#pragma once

#include <QtCore/qglobal.h>

#ifdef WORKSPACEPLUGIN_EXPORT
 #define WORKSPACEPLUGIN_API Q_DECL_EXPORT
#else
 #define WORKSPACEPLUGIN_API Q_DECL_IMPORT
#endif // WORKSPACEPLUGIN_EXPORT

#ifdef TEST_PLUGIN
  #ifdef WORKSPACEPLUGIN_INTERNAL_EXPORT
   #define WORKSPACEPLUGIN_INTERNAL_API Q_DECL_EXPORT
  #else
   #define WORKSPACEPLUGIN_INTERNAL_API Q_DECL_IMPORT
  #endif // WORKSPACEPLUGIN_INTERNAL_EXPORT
#else
  #define WORKSPACEPLUGIN_INTERNAL_API
#endif // TEST_PLUGIN
